# Generated by Django 4.2.3 on 2023-07-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='my_custom_table_name',
        ),
    ]
