# Generated by Django 4.2.3 on 2023-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataTask', '0002_alter_userinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigIntegerField(db_comment='每个文件的id', primary_key=True, serialize=False)),
                ('origin_name', models.CharField(blank=True, db_comment='初始文件名称，始终是一个压缩包，如果不是，人工处理一下', max_length=255, null=True)),
                ('src', models.CharField(blank=True, db_comment='直接提供的文件下载地址，需要将备份目录设置为文件服务器访问目录', max_length=255, null=True)),
                ('origin', models.CharField(blank=True, db_comment='一开始对接时，从哪儿得到这个文件的（群、服务器等），也可能是某个原始文件', max_length=255, null=True)),
                ('get_time', models.DateField(blank=True, db_comment='获取文件的时间', null=True)),
                ('description', models.CharField(blank=True, db_comment='对该文件的来源，包含内容，做一下大致的描述', max_length=255, null=True)),
                ('project_id', models.IntegerField(blank=True, db_comment='该文件隶属于哪个项目', null=True)),
                ('type', models.CharField(blank=True, db_comment='0，代表是原始数据；1，代表是处理过的一些数据', max_length=255, null=True)),
                ('task_name', models.CharField(blank=True, db_comment='该字段主要针对原始数据，有些命名不能明确表达含义，需要另起一个命名', max_length=255, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigIntegerField(db_comment='表id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_comment='实际项目名称', max_length=255, null=True)),
                ('timestamp', models.DateField(blank=True, db_comment='项目开始的大致时间', null=True)),
                ('description', models.CharField(blank=True, db_comment='项目的大致描述', max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, db_comment='项目实际编码', max_length=255, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskBatchList',
            fields=[
                ('id', models.IntegerField(db_comment='任务id，每次新任务，新增一条记录', primary_key=True, serialize=False)),
                ('intro', models.CharField(blank=True, db_comment='简要介绍下此次任务的内容，相当于标题', max_length=255, null=True)),
                ('tag_related_files', models.CharField(blank=True, db_comment='本次任务涉及的文件，从files表中获取id，如果有多个，以英文逗号隔开，如1,2', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_comment='对此次任务的详细描述', max_length=255, null=True)),
                ('start_time', models.DateField(blank=True, db_comment='任务开始时间', null=True)),
                ('end_time', models.DateField(blank=True, db_comment='任务结束时间', null=True)),
                ('file_type', models.CharField(blank=True, db_comment='此次任务设计的文件类型，如果有多个，以英文逗号隔开，如txt,doc,docx', max_length=255, null=True)),
                ('file_number', models.IntegerField(blank=True, db_comment='文件的数量', null=True)),
                ('tools', models.CharField(blank=True, db_comment='使用了什么工具来处理此次任务，如果有多个，以英文逗号隔开，如python,labelstudio', max_length=255, null=True)),
                ('tools_path', models.CharField(blank=True, db_comment='如果是在标注工具或者核验平台上处理的，给出任务路径即可', max_length=255, null=True)),
                ('category_nums', models.CharField(blank=True, db_comment='本次任务的性质：1，标注；2，数据整理，分类，核验等；3，其他；4，待定；', max_length=255, null=True)),
                ('sovled', models.CharField(blank=True, db_comment='该次任务是否完成了：1，完成，0，进行中', max_length=255, null=True)),
                ('source_file_path', models.CharField(blank=True, db_comment='该次任务涉及的源文件路径，可以是文件夹', max_length=255, null=True)),
                ('tag_result_path', models.CharField(blank=True, db_comment='任务结果文件的路径，可以是文件夹', max_length=255, null=True)),
                ('backup_name', models.CharField(blank=True, db_comment='该次任务备份文件名称，一般是zip压缩包', max_length=255, null=True)),
                ('project_id', models.IntegerField(blank=True, db_comment='该次任务隶属于哪个项目', null=True)),
                ('project_batch_id', models.IntegerField(blank=True, db_comment='在每个项目下，对应的batch_id，不同于id，这个id是对应单个项目的', null=True)),
            ],
            options={
                'db_table': 'task_batch_list',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
