# Generated by Django 4.2.3 on 2023-07-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataTask', '0003_files_project_taskbatchlist_delete_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
