/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackGround: typeof import('./components/BackGround.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElLoading: typeof import('element-plus')['ElLoading'] 
    ElMessage: typeof import('element-plus')['ElMessage'] 
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/test.vue')['default']
  }
}
